// Global events
export const $INTERACT_DRAGGED_DOWN = 'INTERACT.DRAGGED_DOWN';
export const $INTERACT_DRAGGED_LEFT = 'INTERACT.DRAGGED_LEFT';
export const $INTERACT_DRAGGED_RIGHT = 'INTERACT.DRAGGED_RIGHT';
